# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.



development:
  secret_key_base: 90a8f64c7ea5f281b5a29618475106fa3a07285600fe8fac4b390405b0bf8f153b1902256379b73a1db4f168a250bb442f4aba272e4cdaaa11a49cf521f5a520
  soundcloudkey: <%= ENV["SOUNDCLOUD_KEY"] %>
  # soundcloudkey: faa62a465cae941ad9b108e2d75e9e7d

test:
  secret_key_base: a501e082579ceeaf7060e9005d7c7d115c13ddd126d9f3c296c6e161c32b6bf3e4ec60b1bf34402b0ba143fff149b678bea60b55c2f8d8e934fd1bedba9fa97b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  soundcloudkey: <%= ENV["SOUNDCLOUD_KEY"] %>
